version: "3"
services:
  user-service:
    image: nghhng/football-booking:user
    ports:
      - "7100:7100"
    restart: always
    networks:
      - football-booking

  facility-service:
    image: nghhng/football-booking:facility
    ports:
      - "7200:7200"
    restart: always
    networks:
      - football-booking

  booking-service:
    image: nghhng/football-booking:booking
    ports:
      - "7300:7300"
    restart: always
    networks:
      - football-booking

  discovery-service:
    image: nghhng/football-booking:discovery
    ports:
      - "7654:7654"
    restart: always
    networks:
      - football-booking

  auth-service:
    image: nghhng/football-booking:auth
    ports:
      - "8001:8001"
    restart: always
    networks:
      - football-booking

  noti-service:
    image: nghhng/football-booking:noti
    ports:
      - "7400:7400"
    restart: always
    networks:
      - football-booking

  redis:
    image: redis:6.2.4-alpine
    container_name: redis-1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass 123456a@
    networks:
      - football-booking
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - football-booking

  kafka0:
    container_name: kafka0
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    #    spring kafka config connect to port 29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:9092,PLAINTEXT_HOST://kafka0:29092,PLAINTEXT_LOCALHOST://localhost:2909
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_LOCALHOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "booking-noti-topic:1:1"
    networks:
      - football-booking
networks:
  football-booking:
volumes:
  redis_data: